import React, { useState, useEffect } from 'react';
import api from '../api/api';
import { getUserData } from '../getUserData';
import './AgentSettings.css';

function AgentSettings(){
 const [profile,setProfile]=useState({username:'',email:'',agency_name:'',idDocument:null,ownershipCertificate:null});
 const [form,setForm]=useState({username:'',email:'',agency_name:'',currentPassword:'',newPassword:''});
 const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [filesExist,setFilesExist]=useState(false); const [agencyNameExists,setAgencyNameExists]=useState(false);
 const user=getUserData(); const token=user?.token; const agentId=user?.userId;
 useEffect(()=>{const fetchProfile=async()=>{if(!agentId){setError('Agent ID not found.');return}try{const r=await api.get(`/api/agentSettings/${agentId}`,{headers:{Authorization:`Bearer ${token}`}});const d=r.data;setProfile({username:d.username||'',email:d.email||'',agency_name:d.agency_name||'',idDocument:d.idDocument||'',ownershipCertificate:d.ownershipCertificate||''});setForm({username:d.username||'',email:d.email||'',agency_name:d.agency_name||'',currentPassword:'',newPassword:''});setFilesExist(d.documentsExist);setAgencyNameExists(d.agencyNameExists)}catch(e){console.error(e);setError('Failed to fetch agent profile')}};if(token)fetchProfile()},[token,agentId]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const files=e=>{const {name,files}=e.target;if(files.length)setProfile({...profile,[name]:files[0]})};
 const update=async e=>{e.preventDefault();setMessage('');setError('');const fd=new FormData();fd.append('username',form.username);fd.append('email',form.email);fd.append('agency_name',form.agency_name);fd.append('idDocument',profile.idDocument);fd.append('ownershipCertificate',profile.ownershipCertificate);try{const r=await api.put('/api/agentSettings/profile',fd,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'multipart/form-data'}});setMessage(r.data.message)}catch(e){setError(e.response?.data?.message||'Failed to update agent profile')}};
 const password=async e=>{e.preventDefault();setMessage('');setError('');try{const r=await api.put('/api/agentSettings/password',{currentPassword:form.currentPassword,newPassword:form.newPassword},{headers:{Authorization:`Bearer ${token}`}});setMessage(r.data.message);setForm({...form,currentPassword:'',newPassword:''})}catch(e){setError(e.response?.data?.message||'Failed to change password')}};
 return <div className="agent-settings-page"><div className="agent-settings-head"><p className="agent-settings-eyebrow">Workspace settings</p><h1>Account & verification</h1><p>Keep your agent profile accurate and complete the information renters need to trust your listings.</p></div>{message&&<div className="agent-settings-message success">{message}</div>}{error&&<div className="agent-settings-message error">{error}</div>}
 <div className="agent-settings-grid"><section className="agent-settings-card"><h3>Agent profile</h3><p>Your public identity and verification details.</p><form className="agent-settings-form" onSubmit={update}>
 <label className="agent-settings-field"><span>Username</span><input type="text" name="username" value={form.username} onChange={change} required/></label>
 <label className="agent-settings-field"><span>Phone / email</span><input type="text" name="email" value={form.email} onChange={change} required/></label>
 <label className="agent-settings-field full"><span>Agency name</span><input type="text" name="agency_name" value={form.agency_name} onChange={change} required={!agencyNameExists} placeholder="Your agency or business name"/></label>
 <label className="agent-settings-field"><span>Government ID</span><input type="file" name="idDocument" accept="image/*" onChange={files} required={!filesExist}/></label>
 <label className="agent-settings-field"><span>Ownership certificate</span><input type="file" name="ownershipCertificate" accept="image/*" onChange={files} required={!filesExist}/></label>
 <button className="agent-settings-submit" type="submit">Save profile changes</button></form></section>
 <aside className="agent-settings-card agent-settings-security"><h3>Verification status</h3><p>Required information for payment eligibility.</p><div className="agent-settings-status"><strong className={filesExist?'status-ok':'status-warning'}>{filesExist?'Documents uploaded':'Documents required'}</strong><span>{filesExist?'Your verification documents are on file.':'Upload your Government ID and ownership certificate.'}</span></div><div className="agent-settings-status"><strong className={agencyNameExists?'status-ok':'status-warning'}>{agencyNameExists?'Agency name added':'Agency name missing'}</strong><span>{agencyNameExists?'Your agency information is present.':'Add an agency name to complete your profile.'}</span></div><h3 style={{marginTop:'22px'}}>Security</h3><p>Update your password regularly.</p><form onSubmit={password}><label className="agent-settings-field"><span>Current password</span><input type="password" name="currentPassword" value={form.currentPassword} onChange={change} required/></label><label className="agent-settings-field"><span>New password</span><input type="password" name="newPassword" value={form.newPassword} onChange={change} required/></label><button className="agent-settings-submit" type="submit">Change password</button></form><p className="agent-settings-note">Your account credentials are used to protect your listings and agent workspace.</p></aside></div></div>;
}
export default AgentSettings;
