import React, { useEffect, useMemo, useRef, useState } from 'react';
import io from 'socket.io-client';
import { Link, useNavigate } from 'react-router-dom';
import { getUserData } from '../getUserData';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowLeft, faArrowRight, faArrowRightFromBracket, faMagnifyingGlass, faPaperPlane, faComments, faCircle, faHouse } from '@fortawesome/free-solid-svg-icons';
import './PrivateChat.css';

const API_URL = process.env.REACT_APP_API_URL || '';
const SOCKET_URL = API_URL || window.location.origin;

const PrivateChat = () => {
  const userData = getUserData();
  const userId = userData?.userId || null;
  const userName = userData?.userName || userData?.username || 'Renty member';
  const navigate = useNavigate();
  const socketRef = useRef(null);
  const bottomRef = useRef(null);
  const [messages,setMessages]=useState([]),[newMessage,setNewMessage]=useState(''),[receiverId,setReceiverId]=useState(userData?.receiverId||null),[receiverName,setReceiverName]=useState(userData?.receiverName||''),[users,setUsers]=useState([]),[searchTerm,setSearchTerm]=useState(''),[chats,setChats]=useState([]),[searching,setSearching]=useState(false),[loading,setLoading]=useState(false),[connected,setConnected]=useState(false);

  const initials=useMemo(()=>userName.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase(),[userName]);
  useEffect(()=>{if(!userId)return;const stored=JSON.parse(localStorage.getItem('recentChats')||'[]');setChats(stored);socketRef.current=io(SOCKET_URL,{transports:['websocket','polling']});socketRef.current.on('connect',()=>setConnected(true));socketRef.current.on('disconnect',()=>setConnected(false));const receive=(message)=>{if(message.senderId===receiverId||message.receiverId===receiverId)setMessages(prev=>[...prev,message]);};socketRef.current.on('receivePrivateMessage',receive);fetch(`${API_URL}/api/chat/history/${userId}`).then(r=>r.ok?r.json():[]).then(data=>{if(Array.isArray(data)){const merged=[...stored,...data].filter(Boolean);setChats(merged);localStorage.setItem('recentChats',JSON.stringify(merged));}}).catch(console.error);return()=>{socketRef.current?.off('receivePrivateMessage',receive);socketRef.current?.disconnect()}},[userId,receiverId]);
  useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:'smooth'})},[messages]);
  useEffect(()=>{if(!receiverId||!userId)return;setLoading(true);fetch(`${API_URL}/api/chat/private/${userId}/${receiverId}`).then(r=>r.ok?r.json():[]).then(data=>setMessages(Array.isArray(data)?data:[])).catch(console.error).finally(()=>setLoading(false))},[receiverId,userId]);
  const selectUser=(u)=>{setReceiverId(u.id);setReceiverName(u.name||u.username||u.email||'Renty member');setUsers([]);const item={receiverId:u.id,receiverName:u.name||u.username||u.email||'Renty member'};const updated=[item,...chats.filter(c=>String(c.receiverId)!==String(u.id))];setChats(updated);localStorage.setItem('recentChats',JSON.stringify(updated));};
  const search=async(e)=>{e?.preventDefault();if(!searchTerm.trim())return;setSearching(true);try{const r=await fetch(`${API_URL}/api/chat/users/${encodeURIComponent(searchTerm.trim())}`);const data=await r.json();setUsers(Array.isArray(data)?data:[])}catch(err){console.error(err);setUsers([])}finally{setSearching(false)}};
  const send=async(e)=>{e.preventDefault();const text=newMessage.trim();if(!text||!receiverId)return;const data={senderId:userId,receiverId,senderName:userName,message:text};socketRef.current?.emit('sendPrivateMessage',data);setMessages(prev=>[...prev,data]);setNewMessage('');try{await fetch(`${API_URL}/api/chat/private`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})}catch(err){console.error('Message save failed:',err)}};
  const logout=()=>{localStorage.removeItem('userData');navigate('/')};
  return <div className="renty-chat-app"><header className="renty-chat-header"><div className="renty-chat-brand"><Link to={userData?.role==='agent'?'/agent-dashboard':'/user-dashboard'}><FontAwesomeIcon icon={faArrowLeft}/></Link><div className="renty-chat-logo"><img src="/images/renty.png" alt="Renty"/><strong>renty<span>.</span></strong></div><div className="renty-chat-title"><span>Renty workspace</span><strong>Messages</strong></div></div><div className="renty-chat-head-actions"><span className="renty-chat-online"><FontAwesomeIcon icon={faCircle}/> {connected?'Connected':'Connecting'}</span><button onClick={logout}><FontAwesomeIcon icon={faArrowRightFromBracket}/> <span>Log out</span></button></div></header>
    <main className="renty-chat-layout"><aside className="renty-chat-sidebar"><div className="renty-chat-sidebar-top"><div><p>Inbox</p><h2>Your conversations</h2></div><span>{chats.length}</span></div><form className="renty-chat-search" onSubmit={search}><FontAwesomeIcon icon={faMagnifyingGlass}/><input value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} placeholder="Search by email…"/><button disabled={searching}>{searching?'…':'Search'}</button></form>{users.length>0&&<div className="renty-chat-results">{users.map(u=><button key={u.id} onClick={()=>selectUser(u)}><div className="renty-chat-avatar">{(u.name||u.username||'R').slice(0,2).toUpperCase()}</div><span><strong>{u.name||u.username||'Renty member'}</strong><small>{u.email}</small></span></button>)}</div>}<div className="renty-chat-list"><button className="renty-chat-support" onClick={()=>{setReceiverId(null);setReceiverName('')}}><div className="renty-chat-avatar dark"><FontAwesomeIcon icon={faComments}/></div><span><strong>Renty support</strong><small>We're here to help</small></span></button>{chats.map(c=><button key={c.receiverId} className={`renty-chat-list-item ${String(c.receiverId)===String(receiverId)?'active':''}`} onClick={()=>selectUser({id:c.receiverId,name:c.receiverName})}><div className="renty-chat-avatar">{(c.receiverName||'R').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><span><strong>{c.receiverName||'Renty member'}</strong><small>Open conversation</small></span><FontAwesomeIcon icon={faArrowRight}/></button>)}</div></aside>
    <section className="renty-chat-window">{receiverId?<><div className="renty-chat-conversation-head"><div className="renty-chat-avatar">{receiverName.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><div><strong>{receiverName}</strong><span><FontAwesomeIcon icon={faCircle}/> Renty member</span></div></div><div className="renty-chat-messages">{loading?<div className="renty-chat-empty"><strong>Loading conversation…</strong></div>:messages.length===0?<div className="renty-chat-empty"><div><FontAwesomeIcon icon={faComments}/></div><strong>Start a conversation</strong><span>Send a message to {receiverName}.</span></div>:messages.map((m,i)=><div key={i} className={`renty-chat-message ${m.senderId===userId?'sent':''}`}><div className="renty-chat-bubble"><p>{m.message}</p><small>{m.timestamp||'Now'}</small></div></div>)}<div ref={bottomRef}/></div><form className="renty-chat-composer" onSubmit={send}><div className="renty-chat-avatar">{initials}</div><input value={newMessage} onChange={e=>setNewMessage(e.target.value)} placeholder="Write a message…"/><button disabled={!newMessage.trim()}><FontAwesomeIcon icon={faPaperPlane}/><span>Send</span></button></form></>:<div className="renty-chat-welcome"><div className="renty-chat-welcome-icon"><FontAwesomeIcon icon={faComments}/></div><h2>Your messages</h2><p>Select a conversation or search for a Renty member to start chatting.</p><Link to={userData?.role==='agent'?'/agent-dashboard':'/user-dashboard'}><FontAwesomeIcon icon={faHouse}/> Back to dashboard</Link></div>}</section></main></div>;
};
export default PrivateChat;
